---
- name: Deploy TMDB Application
  hosts: all
  become: yes

  vars:
    app_repo: "https://github.com/salawadhi/tmdb-devops-challenge.git"
    app_dir: "/var/www/tmdb"
    nginx_conf: "/etc/nginx/sites-available/tmdb"

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install necessary packages
      apt:
        name:
          - git
          - nginx
          - nodejs
          - npm
        state: present

    - name: Clone the application repository
      git:
        repo: "{{ app_repo }}"
        dest: "{{ app_dir }}"
        version: main

    - name: Install node dependencies
      npm:
        path: "{{ app_dir }}"
        state: present

    - name: Build the application
      command: npm run build
      args:
        chdir: "{{ app_dir }}"

    - name: Create Nginx configuration for the app
      copy:
        content: |
          server {
            listen 80;
            server_name _;
            root {{ app_dir }}/public;

            location / {
              try_files $uri /index.html;
            }

            location /api {
              proxy_pass http://localhost:3000;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
            }
          }
        dest: "{{ nginx_conf }}"

    - name: Enable Nginx configuration
      file:
        src: "{{ nginx_conf }}"
        dest: /etc/nginx/sites-enabled/tmdb
        state: link

    - name: Remove default Nginx configuration (if exists)
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes